### ISSUE TITLE
Create predefined roles

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/saml-addon#21]
### Environment

- Platform version: 7.2.x
- Addon version: 0.4-SNAPSHOT

### Description

Create predefined system roles

**Comment by zaharchenko-evgeny** [comment]
## Predefined roles
- **SAML admin** - full access to SAML configuration

**Comment by skatova** [comment]
For **SAML admin** role:
1. Administration → SAML 
2. Select a SAML connection
3. Click Create
4. Try to choose a _Default Access Group_

E.R. _Default Access Group_ was chosen
A.R. Access denied

![image](https://user-images.githubusercontent.com/53561930/80575372-8430ef80-8a14-11ea-99fd-4049f78a3509.png)
