### ISSUE TITLE
Failed to determinate SAML connection after redirecting back from IDP

### ISSUE THREAD

**Issue by glebshalyganov** [cuba-platform/saml-addon#25]
# Environment

- Platform version: 7.2
- Addon version: 0.4.1
- HTTPs enabled
- Browser: Chrome (in most cases)

### Description of the bug or enhancement

- Try login to CUBA app with HTTPs enabled via IDP
- When redirecting back from IDP this error occurs:
```java
java.lang.RuntimeException: Failed to determinate SAML connection
	com.haulmont.addon.saml.saml.internal.impl.SamlConnectionContextProviderImpl.populateConnection(SamlConnectionContextProviderImpl.java:157)
	com.haulmont.addon.saml.saml.internal.impl.SamlConnectionContextProviderImpl.getLocalEntity(SamlConnectionContextProviderImpl.java:109)
	org.springframework.security.saml.SAMLProcessingFilter.attemptAuthentication(SAMLProcessingFilter.java:84)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	com.haulmont.addon.saml.web.security.saml.SamlLoginHttpRequestFilter.doFilter(SamlLoginHttpRequestFilter.java:83)
	org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
```
The root cause of the error is that JSESSIONID cookie doesn't have attribute `SameSite` specified. Chrome defaults it to `SameSite=Lax` and then blocks it because the request was made from a different site (IDP). It leads to invalidating the current session and losing the `tenant` attribute which causes the error above.

### Solution:
Setup `SameSite=None` cookie policy.
1) **Tomcat:**
In the `webapps/app/META-INF/context.xml` specify the CookieProcessor:
```xml
<Context>
   ...
   <CookieProcessor sameSiteCookies="none" />
   ...
</Context>
```
2) **Jetty (UberJAR):**
Open the `web.xml` in the web-module: `web/WEB-INF/web.xml`. Specify the following session-config:
```xml
</web-app>
   ...
    <session-config>
        <cookie-config>
            <comment>__SAME_SITE_NONE__</comment>
        </cookie-config>
    </session-config>
</web-app>
```
Re-build uberJar.

The above methods work for Tomcat (9.0.28 and later) and UberJAR versions that come with CUBA Plugin 7.2.9.

**Comment by beatle01** [comment]
Well, it seems this is not the only cause of this issue. I'm still having trouble getting it to work while the cookie-settings are correct, see the screenshot:
![Google Failed SAML login](https://user-images.githubusercontent.com/5708246/95846324-96e17b80-0d4b-11eb-873c-1ecebae35cab.png)

And this is the logging:
```
^[[33mweb_1_47b84cc076d3 |^[[0m Oct 13, 2020 11:53:46 AM org.apache.catalina.core.StandardWrapperValve invoke
^[[33mweb_1_47b84cc076d3 |^[[0m SEVERE: Servlet.service() for servlet [saml_dispatcher] in context with path [] threw exception java.lang.RuntimeException: Failed to determinate SAML connection
^[[33mweb_1_47b84cc076d3 |^[[0m    at com.haulmont.addon.saml.saml.internal.impl.SamlConnectionContextProviderImpl.populateConnection(SamlConnectionContextProviderImpl.java:157)
^[[33mweb_1_47b84cc076d3 |^[[0m     at com.haulmont.addon.saml.saml.internal.impl.SamlConnectionContextProviderImpl.getLocalEntity(SamlConnectionContextProviderImpl.java:109)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.saml.SAMLProcessingFilter.attemptAuthentication(SAMLProcessingFilter.java:84)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
^[[33mweb_1_47b84cc076d3 |^[[0m     at com.haulmont.addon.saml.web.security.saml.SamlLoginHttpRequestFilter.doFilter(SamlLoginHttpRequestFilter.java:81)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
^[[33mweb_1_47b84cc076d3 |^[[0m     at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
^[[33mweb_1_47b84cc076d3 |^[[0m     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
^[[33mweb_1_47b84cc076d3 |^[[0m     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
^[[33mweb_1_47b84cc076d3 |^[[0m     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
^[[33mweb_1_47b84cc076d3 |^[[0m     at java.lang.Thread.run(Thread.java:748)
```

This is from accessing the SAML authentication using Google. Everything is setup correctly and works as expected as long as the authentication is initiated from the Cuba application. When starting it from the IDP (Google) the browser ends up at <appurl>/saml/SSO and the application shows the logging as shown above.

Somehow, the connection cannot be determined even if the start url is set to include the connection path (/saml/login?tenant=....):
![Google SAML settings](https://user-images.githubusercontent.com/5708246/95847295-d361a700-0d4c-11eb-8cca-649e8b9e52bd.png)

If this url is pasted into the browser directly, it all works fine, just not when started from G Suite as a SAML app.

Any suggestions?

**Comment by glebshalyganov** [comment]
Hi, @beatle01 
Thank you for your post.
I don't have much experience with G Suite, and I'm not quite familiar with the authentication flow "starting from the IDP (Google)".
Assumed that cookie settings are correct, it looks like IDP doesn't visit the Start-URL before accessing the ACS-URL. Could you please check this suggestion via logging/debugging?

Regards,
Gleb

**Comment by beatle01** [comment]
Hi @glebshalyganov 

Thanks for your reply, much appreciated.

We have had some support and feedback from Google and this was part of their statement:
> The Start URL section in the service provider settings is the Relay state URL. ... 
... The Relay state URL is an identifier for the resource at the SP that the IDP will redirect the user to (after successful login). It is a way to make the process of SSO more transient to the user because they are redirected again to the same page they originally requested at the SP.

So in effect, the start URL as configured in Google is to be triggered **after** the SAML authentication - not before. And that's exactly what is happening. See the [detailed flow](https://lh3.googleusercontent.com/ijxXNNLYFPLlMEjBf5yWS2xRiLDRRXUcYyX8mY61dPa1wfxpWExmdMazM7kEWWVjf6s=w661). 

This is different from the SP initiated flow. In our tests, we found that the SP initiated flow works fine, no problems there. But that seems to be working mainly because the application is to set the following attribute in the session from within the login screen controller:
`VaadinSession.getCurrent().getSession().setAttribute(SamlSessionPrincipal.SAML_CONNECTION_CODE, connection.getSsoPath());`

When using the IdP initiated flow however, this attribute is not set as the first call is to /saml/SSO rather than the login screen controller (see the detailed flow as linked before). The logging which the application then generates matches this finding:
`Failed to determinate SAML connection`

In our opinion, this is an issue of the SAML add-on implementation. Hope you agree. Or is there another solution that we do not know of?

Regards,
-b

**Comment by glebshalyganov** [comment]
@beatle01 , in this case maybe you should put the `tenant` parameter to the ACS-URL (`/saml/SSO?tenant=....`)?

**Comment by beatle01** [comment]
@glebshalyganov,

Yes, we thought of that as well given the problem description but that doesn't work. Somehow the IdP, client (browser) and SP get into a loop which goes back and forth but no login whatsoever...

Actually, we tried a number of scenarios but without success. In our opinion, the SP (so the SAML add-on) should be able to determine the proper connection given the IdP identity which the IdP provides in its (initial) call. That at least seems the way this should work given the documentation.

Regards,
-b

**Comment by glebshalyganov** [comment]
@beatle01 , i tried performing an IDP initialized SSO with https://idp.ssocircle.com/ and it worked, but it looks like putting the tenant parameter to the ACS-URL is not quite correct.
Instead of it, i've set this parameter in the code. Could you please try this too and check if it works for your case:
1) Extend from `org.springframework.security.saml.SAMLProcessingFilter` class and set tenant parameter before processing the message:
```java
public class SAMLProcessingFilterImpl extends SAMLProcessingFilter {
    public SAMLProcessingFilterImpl() {
    }

    @Override
    public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) throws AuthenticationException {
        request.getSession().setAttribute("tenant", "google");
        return super.attemptAuthentication(request, response);
    }
}
```
2) Override saml-addon configuration by creating a file `saml-dispatcher-spring.xml` in the web-module. Copy and paste the content of [saml-dispatcher-spring.xml](https://github.com/cuba-platform/saml-addon/blob/master/modules/web/src/com/haulmont/addon/saml/saml-dispatcher-spring.xml). Replace the class of the `samlWebSSOProcessingFilter` bean with your `SAMLProcessingFilterImpl` implementation.
3) In the web-app.properties set the property pointing to the saml configuration file: 
`saml.springContextConfig = com/sample/.../saml-dispatcher-spring.xml`.

Regards,
Gleb

**Comment by beatle01** [comment]
@glebshalyganov,

The "google" in your code is the entity id as configured on the SAML connection in the app? If so, this would not be a general solution, correct? It would be more of a default?

Anyway, will give it a try and let you know.

Regards,
-b

**Comment by glebshalyganov** [comment]
>The "google" in your code is the entity id as configured on the SAML connection in the app? If so, this would not be a general solution, correct? It would be more of a default?

Yes, it's just an experiment. If it works, we will think about a general solution for this problem.

**Comment by beatle01** [comment]
Hi @glebshalyganov 

Seems to work for the Google setup ! That's a step forward.

However, any other SAML connection that we have configured seems not to work anymore. Which I guess makes sense given the 'hard coded' tenant id that is being set.

So, how should we go from here?

Regards,
-b

**Comment by glebshalyganov** [comment]
Hi, @beatle01 

Thank you for your reply.
Apparently the add-on wasn't designed to support the case with IDP initiated SSO. Currently it is required to set the `tenant`(SAML connection code) session attribute before communicating with IDP, otherwise it doesn't work. I've created a separate [ticket](https://github.com/cuba-platform/saml-addon/issues/26) for this problem.

>However, any other SAML connection that we have configured seems not to work anymore. Which I guess makes sense given the 'hard coded' tenant id that is being set.
>
>So, how should we go from here?

As a workaround, you can add more code to the sample class `SAMLProcessingFilterImpl` and determine the appropriate SAML connection based on some information from IDP request (URL, parameters, XML data, etc). It is still not a generic solution, but at least it can help you to overcome this problem.

Regards,
Gleb

**Comment by beatle01** [comment]
Hi @glebshalyganov 

Thanks again. Yes it would be great if this was fixed / supported. Will closely monitor progress on that one.

For now, I managed to get the other SAML connections working as well by only setting the attribute if not already set before:
```java
public class SAMLProcessingFilterImpl extends SAMLProcessingFilter {
    public SAMLProcessingFilterImpl() {
    }

    @Override
    public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) throws AuthenticationException {
       if (request.getSession().getAttribute("tenant") == null)
           request.getSession().setAttribute("tenant", "google");
       return super.attemptAuthentication(request, response);
    }
}
```
This seems to work in our scenario and I consider it a valid workaround for now. 

Regards,
-b
